#!/bin/bash
apt-get install cmake -y
apt-get install screen wget gcc build-essential g++ make -y
wget https://raw.githubusercontent.com/virtualos/BadVPN/master/badvpn-1.999.130.tar.gz
tar xf badvpn-1.999.130.tar.gz
cd badvpn-1.999.130/
cmake ~/badvpn-1.999.130 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
echo "BadVPN port is 7300"
badvpn-udpgw --listen-addr 127.0.0.1:7300 > /dev/null &
rm /root/badvpn
echo "BadVPN Installed Successfully!"
