#!/bin/bash
apt update && apt upgrade -y
apt install cmake -y
apt install screen wget gcc build-essential g++ make -y
wget https://raw.githubusercontent.com/virtualos/BadVPN/master/badvpn-1.999.130.tar.gz
tar xf badvpn-1.999.130.tar.gz
cd badvpn-1.999.130/
cmake ~/badvpn-1.999.130 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
badvpn-udpgw --listen-addr 127.0.0.1:7302 > /dev/null &
rm /root/badvpn && rm /root/badvpn-1.999.130.tar.gz

cat >  /etc/systemd/system/videocall.service << ENDOFFILE
[Unit]
Description=UDP forwarding for badvpn-tun2socks
After=nss-lookup.target

[Service]
ExecStart=/usr/local/bin/badvpn-udpgw --loglevel none --listen-addr 127.0.0.1:7302 --max-clients 999
User=videocall

[Install]
WantedBy=multi-user.target
ENDOFFILE
useradd -m videocall
systemctl enable videocall
systemctl start videocall

echo "Installed Successfully!"
